### ISSUE TITLE
[DUX-1499] Support running an application

### ISSUE THREAD

**Issue by 9999years** [MercuryTechnologies/ghciwatch#143]
It's nice to run an application like a web server instead of running tests. This may require some additional hooks.

<sub>From [SyncLinear.com](https://synclinear.com) | [DUX-1499](https://linear.app/mercury/issue/DUX-1499/support-running-an-application)</sub>

**Comment by running-grass** [comment]
@9999years 

Thank you for implementing this feature. Now that the issue has been marked as completed, could you provide some guidance on how to use ghciwatch to run a server application? Specifically:

1. Are there any new configuration options or commands to enable server mode?
2. Is there documentation available on how to set up ghciwatch for running and auto-reloading a web server or similar application?
3. Are there any best practices or examples you can share for using this new functionality?

Any information on how to effectively utilize this new feature would be greatly appreciated by the community.

**Comment by 9999years** [comment]
Filed a documentation ticket at #315, see https://github.com/MercuryTechnologies/ghciwatch/issues/315#issuecomment-2289297642 for an initial response (though there's still work to be done for this feature).

**Comment by LightAndLight** [comment]
Right, `GhciStdin::run_command` is synchronous:

https://github.com/MercuryTechnologies/ghciwatch/blob/cfd9de8f51779689e16f48bb53c1825b95a8cf2d/src/ghci/mod.rs#L921-L923

which calls

https://github.com/MercuryTechnologies/ghciwatch/blob/cfd9de8f51779689e16f48bb53c1825b95a8cf2d/src/ghci/stdin.rs#L28-L46

**Comment by 9999years** [comment]
@LightAndLight Would you open a new ticket for non-terminating applications? I'd really like to hear a proposed design, too, since I'm not sure how I'd implement that. (Maybe use something to save a binding corresponding to the async action...? But I think that various commands `ghciwatch` runs will clear bindings...)

**Comment by LightAndLight** [comment]
https://github.com/MercuryTechnologies/ghciwatch/issues/325
