### ISSUE TITLE
docs for tasty usage

### ISSUE THREAD

**Issue by mwotton** [MercuryTechnologies/ghciwatch#318]
### Describe the feature you’d like to be implemented

There are a few tricks necessary to get Tasty running well under ghciwatch, like the bubblewrap buffering trick noted in #317 , as well as using tasty-autocollect rather than tasty-discover (as changes in the generated file under tasty-discover are not picked up.)

I'm happy to write it up, but is there an appropriate place to put docs on integration with specific test-running suites?

**Comment by 9999years** [comment]
> I'm happy to write it up, but is there an appropriate place to put docs on integration with specific test-running suites?

What if we add a new section in `docs` and put it in a new page under there?

Like "Integrating ghciwatch with other tools" and a "Tasty" page under that.

**Comment by mwotton** [comment]
sounds great! i think the test-dev trick of using a single component used in the tests that happens to include everything might be another nice thing to document under that - while it's a good trick until multiple components works smoothly, it does require some changes in hie.yaml to load that component in LSP (otherwise you get errors about a file being part of multiple components)

**Comment by 9999years** [comment]
Closed in #321
