### ISSUE TITLE
[DUX-1314] gRPC for server mode

### ISSUE THREAD

**Issue by 9999years** [MercuryTechnologies/ghciwatch#35]
json+newlines for transport is kinda hacky. Might be nice to do JSON RPC with HTTP-like headers [like language-server-protocol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#contentPart) does or gRPC.

<sub>From [SyncLinear.com](https://synclinear.com) | [DUX-1314](https://linear.app/mercury/issue/DUX-1314/grpc-for-server-mode)</sub>

**Comment by evanrelf** [comment]
IMO JSON is very pragmatic.

- Very low barrier to entry. Haskell has gRPC libraries but they aren't as nice/easy/familiar as good old `aeson`.
- Performance should be good enough, and I think GHCi would be the bottleneck anyways.

Whether that be JSONL or JSON RPC, I don't have a strong preference.
